---
title: "Netflix EDA"
params:
  anal_date:
  default_fold:
author: "Kim Yong Kyeom"
date: "`r params$anal_date`"
output: 
  html_document:
    toc: true
    toc_depth: 2
    toc_float: true
---

<style>
.main-container {
  max-width: 1000px;
  margin-legt: auto;
  margin_right: auto;
}
</style>

```{r setup, include=FALSE, warning=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, include=FALSE, warning=FALSE, message=FALSE}
#### 0. Setting ####
TODAY        <- params$anal_date
DEFAULT_FOLD <- params$default_fold


#### 1. Library ####
package <- c("data.table", "tidyverse", "lubridate", "scales", "ggrepel", "gridExtra",
             "DescTools", "DataExplorer",
             "rmarkdown", "knitr", "kableExtra")
sapply(package, require, character.only = TRUE)


#### 2. Load Data ####
netflix_Data <- fread(sprintf("%s/01.data/netflix_titles.csv", DEFAULT_FOLD))
colnames(netflix_Data) <- toupper(colnames(netflix_Data))


#### 3. Define User's functions ####
fnTransDate <- function(InputDate){
  
  # InputDate <- netflix_Data$DATE_ADDED[2]
  # InputDate <- " April 1, 2014"
  
  if( nchar(InputDate) <= 1 | is.na(InputDate) ){
    OutputDate <- NA
  } else {
    Data_Split <- str_split(gsub(",", "", InputDate), pattern = " ")[[1]]
    Data_Split <- Data_Split[nchar(Data_Split) > 0]
    
    Data_Year  <- Data_Split[3]
    Data_Month <- sprintf("%02d", (1:NROW(month.name))[month.name == Data_Split[1]])
    Data_Day   <- sprintf("%02d", as.numeric(Data_Split[2]))
    
    OutputDate <- sprintf("%s-%s-%s", Data_Year, Data_Month, Data_Day)
  }
  
  return(OutputDate)
}
#############################################

netflix_Data[, DATE_ADDED := sapply(DATE_ADDED, function(x) { fnTransDate(x) })]

```


# 1. Data 구조

```{r, echo=FALSE, include=TRUE, warning=FALSE, message=FALSE, comment=NA, background=FALSE, opting="", results="markup", fig.width=15, fig.height=9}

cat("\n\n")
cat("Structure of Data set")
cat("\n\n")

cat("\n\n")
str(netflix_Data)
cat("\n\n")

cat("\n\n")
cat("Unique Value CNT of each columns")
cat("\n\n")

UniqueValueCNT_DT <- netflix_Data %>% 
  sapply(function(x) NROW(unique(x))) %>% 
  as.data.frame() %>% 
  rownames_to_column() %>% 
  setnames(c("COLUMN", "UNQ_CNT")) %>% 
  dplyr::arrange(desc(UNQ_CNT))

UniqueValueCNT_DT %>% 
  kable("markdown") %>% 
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"),
                full_width = FALSE,
                position = "float_right") %>% 
  print()

UniqueValueCNT_DT %>% 
  ggplot(aes(x = reorder(COLUMN, UNQ_CNT, sum), y = UNQ_CNT)) +
  geom_bar(stat = "identity") +
  coord_flip() +
  geom_hline(yintercept = NROW(netflix_Data)) +
  geom_label(aes(x = floor(NROW(UniqueValueCNT_DT) / 2), 
                 y = NROW(netflix_Data),
                 label = "Total NROW")) +
  labs(x = "COLUMN", title = "Unique value's CNT of each columns") +
  theme(plot.title = element_text(hjust = 0.5))

```


```{r, echo=FALSE, include=TRUE, warning=FALSE, message=FALSE, comment=NA, background=FALSE, opting="", results="asis", fig.width=15, fig.height=9}

## 변수별 단별량 EDA
Uniq_Variable_LS <- colnames(netflix_Data) %>% unique %>% .[order(.)]
Uniq_Variable_LS <- Uniq_Variable_LS[!grepl(pattern = "SHOW_ID|DESCRIPTION", Uniq_Variable_LS)]

cat("\n\n")
cat("# 2. 단변량 EDA {.tabset}")
cat("\n\n")

for( i0 in 1:NROW(Uniq_Variable_LS) ){
  
  cat("\n\n")
  cat(sprintf("## %s. %s", i0, Uniq_Variable_LS[i0]))
  cat("\n\n")
  
  tmpDesc <- suppressMessages(Desc(netflix_Data %>% select_(.dots = Uniq_Variable_LS[i0]),
                                   plotit = FALSE))
  
  tmpDesc_Text <- capture.output(tmpDesc)
  tmpDesc_Text <- paste0("\t\t", tmpDesc_Text)
  
  cat("\n\n")
  cat(sprintf("### Description of %s", Uniq_Variable_LS[i0]))
  cat("\n\n")
  
  cat("\n\n")
  for( j0 in 1:NROW(tmpDesc_Text) ){
    cat(tmpDesc_Text[j0], "\n")
  }
  cat("\n\n")
  
  plot(tmpDesc)
}


```

# 3. Data 특성

```{r, echo=FALSE, include=TRUE, warning=FALSE, message=FALSE, comment=NA, background=FALSE, opting="", results="markup", fig.width=15, fig.height=12}

cat("\n\n")
cat("Number of Shows available in Netflix as Time")
cat("\n\n")

netflix_Data %>% 
  .[, list(CONTENTS_CNT = NROW(unique(SHOW_ID))),
    by = c("DATE_ADDED", "TYPE")] %>% 
  .[order(TYPE, DATE_ADDED)] %>% 
  dplyr::group_by(TYPE) %>% 
  dplyr::mutate(TOTAL_CONTENTS_CNT = cumsum(CONTENTS_CNT),
                LABEL = ifelse(DATE_ADDED == max(DATE_ADDED, na.rm = TRUE), TYPE, NA)) %>% 
  dplyr::mutate(DATE_ADDED = as.Date(DATE_ADDED)) %>% 
  ggplot(aes(x = DATE_ADDED, y = TOTAL_CONTENTS_CNT, col = TYPE)) +
  geom_line() +
  scale_x_date(date_breaks = "3 years", date_labels = "%Y", minor_breaks = "1 years") +
  theme(legend.position = "none") +
  geom_text_repel(aes(label = LABEL), na.rm = TRUE) +
  labs(y = "", title = "Number of available Movies / TV Shows in Netfix") +
  theme(plot.title = element_text(hjust = 0.5))


cat("\n\n")
cat("For each Countries, Number of Shows produced")
cat("\n\n")

fnSelectTOP <- function(Data, Top_CNT = 10){
  
  # Data <- netflix_Data %>%
  #   .[, list(CNT = NROW(unique(SHOW_ID))),
  #     by = c("COUNTRY", "TYPE")] %>% 
  #   .[TYPE == "Movie"] %>% 
  #   as.data.frame()
  
  returnData <- Data %>% 
    dplyr::arrange(desc(CNT)) %>% 
    .[1:Top_CNT, ]
  
  return(returnData)
}

netflix_Data %>%
  .[, list(CNT = NROW(unique(SHOW_ID))),
    by = c("COUNTRY", "TYPE")] %>% 
  group_by(TYPE) %>% 
  do(fnSelectTOP(., Top_CNT = 10)) %>% 
  ungroup() %>% 
  ggplot(aes(x = reorder(COUNTRY, -CNT, sum), y = CNT)) + 
  geom_bar(stat = "identity") +
  labs(x = "COUNTRY", y = "CNT") + 
  facet_wrap(~ TYPE, scales = "free") 


cat("\n\n")
cat("Most frequent Movie / TV Show Categories")
cat("\n\n")

netflix_CategoryData <- netflix_Data %>% 
  dplyr::select(SHOW_ID, TYPE, LISTED_IN) %>% 
  tidyr::separate_rows(LISTED_IN, sep = ",") %>% 
  setnames(c("LISTED_IN"), c("SHOW_CATEGORY")) %>% 
  dplyr::mutate(SHOW_CATEGORY = 
                  case_when(!grepl(pattern = "^\\s", SHOW_CATEGORY) ~ SHOW_CATEGORY,
                            TRUE ~ substr(SHOW_CATEGORY, 2, nchar(SHOW_CATEGORY))
                  )
  ) %>% 
  setDT()
# netflix_CategoryData$SHOW_CATEGORY %>% unique %>% .[order(.)]

netflix_CategoryData %>%
  .[, list(CNT = NROW(unique(SHOW_ID))),
    by = c("SHOW_CATEGORY", "TYPE")] %>% 
  group_by(TYPE) %>% 
  do(fnSelectTOP(., Top_CNT = 10)) %>% 
  ungroup() %>% 
  ggplot(aes(x = reorder(SHOW_CATEGORY, CNT, sum), y = CNT)) + 
  geom_bar(stat = "identity") +
  labs(x = "SHOW_CATEGORY", y = "CNT") + 
  facet_wrap(~ TYPE, scales = "free") +
  # theme(axis.text.x = element_text(angle = 60, hjust = 0.5, vjust = 0.5))
  coord_flip()


cat("\n\n")
cat("Correlation plot of Categories")
cat("\n\n")

netflix_Category_CorrData <- rbind(
  data.table::CJ(
    TYPE       = 'Movie',
    CATEGORY_1 = netflix_CategoryData[TYPE == 'Movie']$SHOW_CATEGORY %>% unique,
    CATEGORY_2 = netflix_CategoryData[TYPE == 'Movie']$SHOW_CATEGORY %>% unique
  ),
  data.table::CJ(
    TYPE       = 'TV Show',
    CATEGORY_1 = netflix_CategoryData[TYPE == 'TV Show']$SHOW_CATEGORY %>% unique,
    CATEGORY_2 = netflix_CategoryData[TYPE == 'TV Show']$SHOW_CATEGORY %>% unique
  )
)

## CATEGORY_1, CATEGORY_2 둘 다 가지는 SHOW_ID의 CNT
netflix_Category_CorrData$MATCH_CNT <-
  apply(
    netflix_Category_CorrData,
    MARGIN = 1,
    function(x) {
      NROW(intersect(
        netflix_CategoryData[TYPE == x['TYPE'] & SHOW_CATEGORY == x['CATEGORY_1']]$SHOW_ID,
        netflix_CategoryData[TYPE == x['TYPE'] & SHOW_CATEGORY == x['CATEGORY_2']]$SHOW_ID
      )
      )
    }
  )

netflix_Category_CorrData <- netflix_Category_CorrData %>% 
  .[CATEGORY_1 < CATEGORY_2 & (MATCH_CNT > 0)]


CorrPlot_Movie <- netflix_Category_CorrData %>% 
  .[TYPE == "Movie"] %>% 
  ggplot() +
  geom_tile(aes(x = CATEGORY_1, y = CATEGORY_2, fill = MATCH_CNT)) +
  scale_fill_distiller(palette = "Spectral") +
  theme(legend.position = "bottom",
        axis.text.x = element_text(angle = 90, hjust = 0.5, vjust = 0.5)) +
  labs(title = "Movie's Correlation plot of Category", x = "", y = "")

CorrPlot_TV <- netflix_Category_CorrData %>% 
  .[TYPE == "TV Show"] %>% 
  ggplot() +
  geom_tile(aes(x = CATEGORY_1, y = CATEGORY_2, fill = MATCH_CNT)) +
  scale_fill_distiller(palette = "Spectral") +
  theme(legend.position = "bottom",
        axis.text.x = element_text(angle = 90, hjust = 0.5, vjust = 0.5)) +
  labs(title = "TV Show's Correlation plot of Category", x = "", y = "")


gridExtra::grid.arrange(CorrPlot_Movie, CorrPlot_TV, ncol = 2)



cat("\n\n")
cat("Actor / Director's Frequency of appearance in Movie / TV Show")
cat("\n\n")

netflix_People <- netflix_Data %>% 
  dplyr::select(SHOW_ID, CAST, DIRECTOR) %>% 
  melt(id.vars = c("SHOW_ID")) %>% 
  setnames(c("SHOW_ID", "ROLE", "PERSON")) %>% 
  dplyr::mutate_if(is.factor, as.character) %>% 
  dplyr::filter(PERSON != "") %>% 
  tidyr::separate_rows(PERSON, sep = ",") %>% 
  dplyr::mutate(PERSON = 
                  case_when(!grepl(pattern = "^\\s", PERSON) ~ PERSON,
                            TRUE ~ substr(PERSON, 2, nchar(PERSON))
                  )
  ) %>% 
  setDT()

netflix_People %>% 
  .[, list(CNT = NROW(unique(SHOW_ID))),
    by = c("ROLE", "PERSON")] %>% 
  group_by(ROLE) %>% 
  do(fnSelectTOP(., Top_CNT = 10)) %>% 
  ungroup() %>% 
  ggplot(aes(x = reorder(PERSON, CNT, sum), y = CNT)) + 
  geom_bar(stat = "identity") +
  labs(x = "PERSON", y = "CNT") + 
  facet_wrap(~ ROLE, scales = "free") +
  coord_flip()


```





# 4. AutoEDA : DataExplorer Package

```{r, echo=FALSE, include=TRUE, warning=FALSE, message=FALSE, comment=NA, background=FALSE, opting="", results="asis", fig.width=15, fig.height=12}

cat("\n\n")
cat("Run R Command : create(~)")
cat("\n\n")

invisible(
  create_report(netflix_Data,
                output_file = sprintf("NetflixData_AutoEDA_%s.html", gsub("-", "", TODAY)),
                output_dir  = sprintf("%s/03.result", DEFAULT_FOLD),
  )
)
```
